.PHONY: init3
init3:
	pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple --verbose -r requirements.txt

.PHONY: init
init:
	pip install -i https://pypi.tuna.tsinghua.edu.cn/simple --verbose -r requirements.txt